version: "1"
rules: # Array of rules
  - base: master                # Required. Target branch
    upstream: Binaryify:master  # Required. Must be in the same fork network.
    mergeMethod: rebase          # Optional, one of [none, merge, squash, rebase, hardreset], Default: hardreset.
